name: Auto Merge PR

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write
  contents: write
  actions: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log the event data to debug trigger
      - name: Log Event Data
        run: echo "${{ toJson(github.event) }}"

      # Step 3: Install GitHub CLI to perform PR merge
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/github-cli.repo | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      # Step 4: Wait for PR checks to complete (CI checks, etc.)
      - name: Wait for PR checks to complete
        uses: actions/github-script@v6
        with:
          script: |
            const checkRuns = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });

            const statuses = checkRuns.data.check_runs.map(run => run.conclusion);
            if (!statuses.every(status => status === 'success')) {
              core.setFailed("Not all checks have passed. Exiting.");
            }

      # Step 5: Merge the PR once all checks pass
      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Attempting to merge PR..."
          gh pr merge "$GITHUB_REF_NAME" --merge --delete-branch
